site_name: CARLA Simulator
repo_url: https://github.com/carla-simulator/carla
docs_dir: Docs
edit_uri: 'edit/master/Docs/'
theme: readthedocs
extra_css: [extra.css]
extra_javascript: [extra.js]

nav:
- Home: 'index.md'
- Getting started:
  - 'Introduction': 'start_introduction.md'
  - 'Quick start package installation': 'start_quickstart.md'
  - 'First steps' : 'tuto_first_steps.md'
  - 'Building CARLA' : 'build_carla.md'

- Next steps:
  - 'Content authoring':
    - 'Authoring maps': 'tuto_content_authoring_maps.md'


- CARLA topics:
  - 'Foundations': 'foundations.md'
  - 'Actors': 'core_actors.md'
  - 'Maps': 'core_map.md'
  - 'Sensors and data': 'core_sensors.md'
  - 'Traffic' : 'ts_traffic_simulation_overview.md'
  - '3rd party integrations': '3rd_party_integrations.md' 
  - 'Development': 'development_tutorials.md'
  - 'Custom assets': 'custom_assets_tutorials.md'

- Resources:
  - 'Blueprint library': 'bp_library.md'
  - 'Python API': 'python_api.md'  
  - 'C++ reference': 'ref_cpp.md'  

- Contributing:
  - 'Guidelines': 'cont_contribution_guidelines.md' 
  - 'Coding standards': 'cont_coding_standards.md'
  - 'Documentation standard': 'cont_doc_standard.md'
 
markdown_extensions:
  - admonition 
 
