site_name: CARLA Simulator
repo_url: https://github.com/carla-simulator/carla
docs_dir: Docs
edit_uri: 'edit/master/Docs/'
theme: readthedocs
extra_css: [extra.css]
extra_javascript: [extra.js]

nav:
- Home: 'index.md'
- Getting started:
  - 'Introduction': 'start_introduction.md'
  - 'Quick start package installation': 'start_quickstart.md'
  - 'First steps' : 'tuto_G_getting_started.md'
  
- CARLA components:
  - 'Foundations': 'core_concepts.md'
  - 'Actors': 'core_actors.md') '
  - 'Maps': 'core_map.md'
  - 'Sensors and data': 'core_sensors.md'
  - 'Traffic' : 'ts_traffic_simulation_overview.md'

- Resources:
  - 'Python API reference': 'python_api.md'
  - 'Blueprint Library': 'bp_library.md'
  - 'C++ reference' : 'ref_cpp.md'

- Tutorials:
  - 'Traffic': 'tuto_G_traffic_manager.md' 
  - 'Rendering': 'tuto_G_texture_streaming.md'
  - 'Sensors': 'tuto_G_instance_segmentation_sensor.md' 
  - 'Actors': 'tuto_G_pedestrian_bones.md'
  - 'Maps': 'tuto_M_custom_map_overview.md'  
  - 'Integrations': 'tuto_G_chrono.md' 
  - 'Custom assets': 'tuto_A_add_vehicle.md' 
  - 'Development': 'tuto_D_contribute_assets.md'

- Resources:
  - 'Blueprint library': 'bp_library.md'
  - 'Python API': 'python_api.md'  
  - 'C++ reference': 'ref_cpp.md'   

markdown_extensions:
  - admonition
